- name: Get download url
  shell: curl -s "https://api.github.com/repos/{{ servezero_app_github_user }}/{{ servezero_app_github_repo }}/tags" | grep "tarball_url" | sed -n '/[ \t]*"tarball_url"/p' | head -n 1 | sed -e 's/[ \t]*".*":[ \t]*"\(.*\)".*/\1/'
  register: app_archive_url
  
- fail:
    msg: "GitHub archive with No tags"
  when: app_archive_url.stdout == ""

- name: Download archive
  unarchive:
    src: "{{ app_archive_url.stdout }}"
    dest: "{{ servezero_app_path | dirname }}"
    remote_src: yes
  when: app_archive_url.stdout is defined

# - name: Remove directory
#   shell: rm -rf "{{ servezero_app_path }}"
#   when: app_archive_url.stdout is defined
