##########################################
# ServeZero Webアプリケーションインストール
##########################################
- name: Get download url
  shell: curl -s "https://api.github.com/repos/{{ servezero_app_github_user }}/{{ servezero_app_github_repo }}/tags" | grep "tarball_url" | sed -n '/[ \t]*"tarball_url"/p' | head -n 1 | sed -e 's/[ \t]*".*":[ \t]*"\(.*\)".*/\1/'
  register: app_archive_url

- name: Download archive
  unarchive:
    src: "{{ app_archive_url.stdout }}"
    dest: "{{ servezero_app_download_path }}"
    remote_src: yes
  when: app_archive_url.stdout is defined

- name: Move directory
  shell: mv "{{ servezero_app_github_user }}-{{ servezero_app_github_repo }}-"* "{{ servezero_app_github_repo }}"
  args:
    chdir: "{{ servezero_app_download_path }}"
  when: app_archive_url.stdout is defined

- name: Clean up directory
  shell: find ./ -type f -name ".gitkeep" -delete
  args:
    chdir: "{{ servezero_app_download_path }}/{{ servezero_app_github_repo }}"
  when: app_archive_url.stdout is defined
